[project]
name = "agemo"
version = "2.6.0"
description = "Agemo is a GUI for Hyprpaper"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.2.1",
    "pyqt6>=6.9.1",
    "requests>=2.32.5",
]

[tool.ruff]
lint.select = [
    "RUF001", # ambiguous-unicode-character-string
    "RUF002", # ambiguous-unicode-character-docstring
    "RUF003", # ambiguous-unicode-character-comment
]
